version: '3.7'
services:
  app:
    container_name: 'car-rental-app'
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm start"
    ports:
      - 4200:4200
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
volumes:
  node_modules: