version: '3.9'

services:
  app:
    container_name: 'app'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge